# SkyBlock-in-Vanilla config.  There are a few options you can tweak here.

chat:
  # Enables a lightweight custom chat that bypasses Mojang chat reporting
  enabled: true

pvp:
  ffa:
    # Enables the Free-For-All PvP arena.
    enabled: false
    # Set the FFA world, spawnpoint, arena bounds, and (optional) safe zone.  For best results, use an enclosed space with barrier walls at least 2 blocks thick.
    world: world
    spawn: { x: 0.5, y: 100.0, z: 0.5, yaw: 0.0, pitch: 0.0 }
    bounds:
      min: [ -50.0, 0.0, -50.0 ]
      max: [ 50.0, 256.0, 50.0 ]
    safezone:
      enabled: false
      min: [ -5.0, 0.0, -5.0 ]
      max: [ 5.0, 256.0, 5.0 ]
  duel:
    # Enables direct 1v1 duels.  Players can send duel requests to each other.
    enabled: false
    # Set the duel world, the two player spawn locations, and the arena bounds.  For best results, use an enclosed space with barrier walls at least 2 blocks thick separate from the Free-For-All Arena.
    world: world
    countdown: 5
    # Each player is set to these for the duration of a duel (hunger is always full); originals are restored after.
    intelligence: 50
    saturation: 5
    # Where PvP duel loadouts are stored.
    loadouts-file: "pvp-loadouts.json"
    # Allows other plugins to read and use the data of this plugin.  Exports data to this file.
    catalog-file: ""
    arena:
      min: [ 100.0, 0.0, 100.0 ]
      max: [ 150.0, 256.0, 150.0 ]
    spawns:
      - { x: 105.5, y: 100.0, z: 125.5, yaw: -90.0, pitch: 0.0 }
      - { x: 145.5, y: 100.0, z: 125.5, yaw: 90.0, pitch: 0.0 }
  stats:
    # Enables stats tracking for duels and/or free-for-alls (recommended).
    enabled: true
    file: "pvp-stats.json"
